sudo: required

language: python

python:
  - "3.6"

services:
  - docker
  
branches:
  only:
    - master
    - staging

before_script:
  - docker-compose -f docker-compose.yml up --build -d

script:
  - docker-compose -f docker-compose.yml run web pipenv run ./manage.py test