# start from an official image
FROM python:3.6

# Set environment variable
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# arbitrary location choice: you can change the directory
RUN mkdir -p /app/src
WORKDIR /app/src

# install our dependencies
# we use --system flag because we don't need an extra virtualenv
COPY Pipfile Pipfile.lock /app/src/
RUN pip install --upgrade pip
RUN pip install pipenv
RUN pipenv install --deploy --system

# copy our project code
COPY . /app/src
RUN python manage.py collectstatic --no-input

# expose the port 8000
EXPOSE 8000

# define the default command to run when starting the container
CMD ["gunicorn", "--chdir", "fitperf_api", "--bind", ":8000", "fitperf_api.wsgi:application"]