version: "3"
services:
    postgres:
        image: postgres:11.0
        container_name: fitperf-postgres
        ports:
            - "15432:5432"
        environment:
            - POSTGRES_USER=dev-user
            - POSTGRES_PASSWORD=dev-password
            - POSTGRES_DB=fitperf
        volumes:
            - fitperf-data:/var/lib/postgresql/data
volumes:
    fitperf-data: