# Generated by Django 2.1.3 on 2018-11-09 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='founder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to=settings.AUTH_USER_MODEL, verbose_name="the movement's creator"),
        ),
        migrations.AlterField(
            model_name='movement',
            name='founder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to=settings.AUTH_USER_MODEL, verbose_name='Createur'),
        ),
        migrations.AlterField(
            model_name='movementsettings',
            name='founder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_settings', to=settings.AUTH_USER_MODEL, verbose_name="the movement setting's creator"),
        ),
    ]
