# Generated by Django 2.1.3 on 2018-11-13 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181109_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='founder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movementsperexercise',
            name='movement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_per_exercise', to='api.Movement'),
        ),
    ]
