# Generated by Django 2.1.3 on 2018-11-14 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181114_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementsettingspermovementsperexercise',
            name='exercise_movement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_linked_to_exercise', to='api.MovementsPerExercise', verbose_name='the settings value for each movement per exercise'),
        ),
        migrations.AlterField(
            model_name='movementsettingspermovementsperexercise',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings_per_movement_linked_to_exercise', to='api.MovementSettings', verbose_name='the setting linked to the movement associated to the exercise'),
        ),
    ]
